# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.26.0/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.26.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/robin/dev/epitech/B-OOP-400-LYN-4-1-raytracer-robin.chabert

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/robin/dev/epitech/B-OOP-400-LYN-4-1-raytracer-robin.chabert

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.26.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.26.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/robin/dev/epitech/B-OOP-400-LYN-4-1-raytracer-robin.chabert/CMakeFiles /Users/robin/dev/epitech/B-OOP-400-LYN-4-1-raytracer-robin.chabert//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/robin/dev/epitech/B-OOP-400-LYN-4-1-raytracer-robin.chabert/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named raytracer

# Build rule for target.
raytracer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raytracer
.PHONY : raytracer

# fast build rule for target.
raytracer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/build
.PHONY : raytracer/fast

Factory/Factory.o: Factory/Factory.cpp.o
.PHONY : Factory/Factory.o

# target to build an object file
Factory/Factory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Factory/Factory.cpp.o
.PHONY : Factory/Factory.cpp.o

Factory/Factory.i: Factory/Factory.cpp.i
.PHONY : Factory/Factory.i

# target to preprocess a source file
Factory/Factory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Factory/Factory.cpp.i
.PHONY : Factory/Factory.cpp.i

Factory/Factory.s: Factory/Factory.cpp.s
.PHONY : Factory/Factory.s

# target to generate assembly for a file
Factory/Factory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Factory/Factory.cpp.s
.PHONY : Factory/Factory.cpp.s

Lights/ILights.o: Lights/ILights.cpp.o
.PHONY : Lights/ILights.o

# target to build an object file
Lights/ILights.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Lights/ILights.cpp.o
.PHONY : Lights/ILights.cpp.o

Lights/ILights.i: Lights/ILights.cpp.i
.PHONY : Lights/ILights.i

# target to preprocess a source file
Lights/ILights.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Lights/ILights.cpp.i
.PHONY : Lights/ILights.cpp.i

Lights/ILights.s: Lights/ILights.cpp.s
.PHONY : Lights/ILights.s

# target to generate assembly for a file
Lights/ILights.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Lights/ILights.cpp.s
.PHONY : Lights/ILights.cpp.s

Main.o: Main.cpp.o
.PHONY : Main.o

# target to build an object file
Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Main.cpp.o
.PHONY : Main.cpp.o

Main.i: Main.cpp.i
.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s
.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Main.cpp.s
.PHONY : Main.cpp.s

Parser/Parser.o: Parser/Parser.cpp.o
.PHONY : Parser/Parser.o

# target to build an object file
Parser/Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Parser/Parser.cpp.o
.PHONY : Parser/Parser.cpp.o

Parser/Parser.i: Parser/Parser.cpp.i
.PHONY : Parser/Parser.i

# target to preprocess a source file
Parser/Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Parser/Parser.cpp.i
.PHONY : Parser/Parser.cpp.i

Parser/Parser.s: Parser/Parser.cpp.s
.PHONY : Parser/Parser.s

# target to generate assembly for a file
Parser/Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Parser/Parser.cpp.s
.PHONY : Parser/Parser.cpp.s

Primitives/Plane.o: Primitives/Plane.cpp.o
.PHONY : Primitives/Plane.o

# target to build an object file
Primitives/Plane.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Primitives/Plane.cpp.o
.PHONY : Primitives/Plane.cpp.o

Primitives/Plane.i: Primitives/Plane.cpp.i
.PHONY : Primitives/Plane.i

# target to preprocess a source file
Primitives/Plane.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Primitives/Plane.cpp.i
.PHONY : Primitives/Plane.cpp.i

Primitives/Plane.s: Primitives/Plane.cpp.s
.PHONY : Primitives/Plane.s

# target to generate assembly for a file
Primitives/Plane.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Primitives/Plane.cpp.s
.PHONY : Primitives/Plane.cpp.s

Primitives/Sphere.o: Primitives/Sphere.cpp.o
.PHONY : Primitives/Sphere.o

# target to build an object file
Primitives/Sphere.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Primitives/Sphere.cpp.o
.PHONY : Primitives/Sphere.cpp.o

Primitives/Sphere.i: Primitives/Sphere.cpp.i
.PHONY : Primitives/Sphere.i

# target to preprocess a source file
Primitives/Sphere.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Primitives/Sphere.cpp.i
.PHONY : Primitives/Sphere.cpp.i

Primitives/Sphere.s: Primitives/Sphere.cpp.s
.PHONY : Primitives/Sphere.s

# target to generate assembly for a file
Primitives/Sphere.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Primitives/Sphere.cpp.s
.PHONY : Primitives/Sphere.cpp.s

Raytracing/Raytracer.o: Raytracing/Raytracer.cpp.o
.PHONY : Raytracing/Raytracer.o

# target to build an object file
Raytracing/Raytracer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Raytracing/Raytracer.cpp.o
.PHONY : Raytracing/Raytracer.cpp.o

Raytracing/Raytracer.i: Raytracing/Raytracer.cpp.i
.PHONY : Raytracing/Raytracer.i

# target to preprocess a source file
Raytracing/Raytracer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Raytracing/Raytracer.cpp.i
.PHONY : Raytracing/Raytracer.cpp.i

Raytracing/Raytracer.s: Raytracing/Raytracer.cpp.s
.PHONY : Raytracing/Raytracer.s

# target to generate assembly for a file
Raytracing/Raytracer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Raytracing/Raytracer.cpp.s
.PHONY : Raytracing/Raytracer.cpp.s

SFML/SFML.o: SFML/SFML.cpp.o
.PHONY : SFML/SFML.o

# target to build an object file
SFML/SFML.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/SFML/SFML.cpp.o
.PHONY : SFML/SFML.cpp.o

SFML/SFML.i: SFML/SFML.cpp.i
.PHONY : SFML/SFML.i

# target to preprocess a source file
SFML/SFML.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/SFML/SFML.cpp.i
.PHONY : SFML/SFML.cpp.i

SFML/SFML.s: SFML/SFML.cpp.s
.PHONY : SFML/SFML.s

# target to generate assembly for a file
SFML/SFML.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/SFML/SFML.cpp.s
.PHONY : SFML/SFML.cpp.s

Transformation/Transformation.o: Transformation/Transformation.cpp.o
.PHONY : Transformation/Transformation.o

# target to build an object file
Transformation/Transformation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Transformation/Transformation.cpp.o
.PHONY : Transformation/Transformation.cpp.o

Transformation/Transformation.i: Transformation/Transformation.cpp.i
.PHONY : Transformation/Transformation.i

# target to preprocess a source file
Transformation/Transformation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Transformation/Transformation.cpp.i
.PHONY : Transformation/Transformation.cpp.i

Transformation/Transformation.s: Transformation/Transformation.cpp.s
.PHONY : Transformation/Transformation.s

# target to generate assembly for a file
Transformation/Transformation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/Transformation/Transformation.cpp.s
.PHONY : Transformation/Transformation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... raytracer"
	@echo "... Factory/Factory.o"
	@echo "... Factory/Factory.i"
	@echo "... Factory/Factory.s"
	@echo "... Lights/ILights.o"
	@echo "... Lights/ILights.i"
	@echo "... Lights/ILights.s"
	@echo "... Main.o"
	@echo "... Main.i"
	@echo "... Main.s"
	@echo "... Parser/Parser.o"
	@echo "... Parser/Parser.i"
	@echo "... Parser/Parser.s"
	@echo "... Primitives/Plane.o"
	@echo "... Primitives/Plane.i"
	@echo "... Primitives/Plane.s"
	@echo "... Primitives/Sphere.o"
	@echo "... Primitives/Sphere.i"
	@echo "... Primitives/Sphere.s"
	@echo "... Raytracing/Raytracer.o"
	@echo "... Raytracing/Raytracer.i"
	@echo "... Raytracing/Raytracer.s"
	@echo "... SFML/SFML.o"
	@echo "... SFML/SFML.i"
	@echo "... SFML/SFML.s"
	@echo "... Transformation/Transformation.o"
	@echo "... Transformation/Transformation.i"
	@echo "... Transformation/Transformation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

